### ISSUE TITLE
The underlying connection was closed: An unexpected error occurred on a send.

### ISSUE THREAD

**Issue by AmitDesai65** [CallFire/eztexting-api-client-csharp#16]
I believe EZTexting recently enhanced the security to Tls2 and hence this code is throwing "The underlying connection was closed: An unexpected error occurred on a send." error. It will be nice to update this project so that it works as before. FYI. I tried following (.Net Framework 4.5) but it didn't work.
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

**Comment by vmalinovskiy** [comment]
Did you try 4.6 version?
For 4.6 version it should work by default. 
Also we'll update api sdk to work with 4.5.

**Comment by AmitDesai65** [comment]
Yes I did and it didn’t work. It must be something on the EZtexting side.

**Comment by vmalinovskiy** [comment]
We have reverted disabling for 1.0 and 1.1 for few days ago.
For now 1.0, 1.1 and 1.2 are supported. (till 14.07).
So can confirm we haven't any problems on our side for now cause a lot of other customers integrations works fine (most of them are on 1.2 already). And for net 4.6 tls 1.2 supported by default.

Probably you have some os limitation? What os do you use?
