### ISSUE TITLE
dll.config doesn't get moved to Temporary asp.net files

### ISSUE THREAD

**Issue by motohead400** [CallFire/eztexting-api-client-csharp#9]
I'm using this in a .NET MVC web project.  The .dll requires a .dll.config file, however the .dll.config file doesn't get moved into the temporary asp.net files folder with the .dll itself by the IIS worker process.  I'm not sure what a workaround for this would be.

**Comment by ZelNaga** [comment]
Hello
Should be fixed now

**Comment by motohead400** [comment]
I just installed version 1.1.31 of this and it still has the same issue.  The dll.config is in my bin directory.  Is there anything else I need to do?

**Comment by ZelNaga** [comment]
maybe this article will help you - https://stackoverflow.com/questions/17167307/dll-config-not-copied-to-temporary-asp-net-files-folder

**Comment by motohead400** [comment]
What is mentioned in the article is what you need to do in the API itself.  I cannot control how the API reads the config file in.

**Comment by motohead400** [comment]
I made this fix in the API and submitted a pull request for it.

**Comment by asvirhun** [comment]
Sorry for delay. This changes was added to 1.1.32 release

**Comment by jnewb1** [comment]
I still have this issue when using ClickOnce. It copies the .dll.config normally when building, but does not copy it when publishing.

**Comment by asvirhun** [comment]
Hi Justin.

Can you please provide detailed "STR" of this problem ?
Thanks.
